In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mpy
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
train.head(50)

,area_assesed,building_id,damage_grade,district_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,has_repair_started,vdcmun_id
0,Both,24385bfd2a2,Grade 4,24,0.0,0,0,0,0,0,0,0,0.0,2489
1,Both,405d1bbebbf,Grade 2,44,0.0,0,0,0,0,0,0,0,1.0,4423
2,Both,351d9bc71f6,Grade 1,36,0.0,0,0,0,0,0,0,0,0.0,3650
3,Building removed,2be3a971166,Grade 5,30,0.0,0,0,0,0,0,0,0,0.0,3016
4,Both,34c7d073ea6,Grade 3,36,0.0,0,0,0,0,0,0,0,0.0,3627
5,Exterior,1f54965821f,Grade 5,21,0.0,0,0,0,0,0,0,0,0.0,2153
6,Both,2beb42eaeee,Grade 2,30,1.0,0,0,0,1,0,0,1,0.0,3018
7,Both,25e8adfd09a,Grade 5,26,0.0,0,0,0,0,0,0,0,0.0,2605
8,Both,1e96b58fa58,Grade 1,21,0.0,0,0,0,0,0,0,0,NaN,2102
9,Both,392cbd772c9,Grade 3,39,0.0,0,0,0,0,0,0,0,1.0,3929
10,Exterior,35074b0c35f,Grade 5,36,0.0,0,0,0,0,0,0,0,0.0,3644
11,Both,1ee123fa622,Grade 4,21,0.0,0,0,0,0,0,0,0,0.0,2122
12,Both,107560bc53d,Grade 2,11,0.0,0,0,0,0,0,0,0,1.0,1131
13,Building removed,355539e8f10,Grade 5,36,0.0,0,0,0,0,0,0,0,0.0,3665
14,Both,d49acbd60b,Grade 2,9,0.0,0,0,0,0,0,0,0,1.0,913
15,Both,28d9006c73e,Grade 5,28,0.0,0,0,0,0,0,0,0,0.0,2807
16,Both,2759f7a1e6f,Grade 4,27,0.0,0,0,0,0,0,0,0,1.0,2704
17,Both,27fd8b93119,Grade 3,27,0.0,0,0,0,0,0,0,0,0.0,2748
18,Both,27597222066,Grade 4,27,0.0,0,0,0,0,0,0,0,1.0,2704
19,Exterior,1b9136a5a0af,Grade 3,30,0.0,0,0,0,0,0,0,0,0.0,3031
20,Both,122d2f8638e,Grade 4,12,0.0,0,0,0,0,0,0,0,0.0,1249
21,Both,25e8fa2ee5a,Grade 4,26,0.0,0,0,0,0,0,0,0,0.0,2605
22,Both,366c9f7bc37,Grade 4,37,0.0,0,0,0,0,0,0,0,1.0,3740
23,Building removed,4372e823ef3,Grade 5,46,1.0,1,0,0,1,0,0,0,1.0,4635
24,Both,2c1404219eb,Grade 4,30,0.0,0,0,0,0,0,0,0,0.0,3029
25,Both,2425e1c30ef,Grade 3,24,0.0,0,0,0,0,0,0,0,0.0,2484
26,Building removed,1d7b8343e6a,Grade 5,20,0.0,0,0,0,0,0,0,0,0.0,2026
27,Building removed,1f45e8dec7e,Grade 5,21,1.0,0,0,0,1,0,0,0,0.0,2149
28,Building removed,2c08cd8e16e,Grade 5,30,0.0,0,0,0,0,0,0,0,0.0,3026
29,Building removed,2a55346ebd2,Grade 5,29,0.0,0,0,0,0,0,0,0,0.0,2909
30,Exterior,2c3594bef82,Grade 4,30,1.0,0,0,0,1,0,0,1,0.0,3038
31,Exterior,2d635dfaa18,Grade 2,31,0.0,0,0,0,0,0,0,0,0.0,3119
32,Both,37f046d4dc3,Grade 1,38,0.0,0,0,0,0,0,0,0,0.0,3844
33,Exterior,11f5152e2ff,Grade 4,12,0.0,0,0,0,0,0,0,0,0.0,1234
34,Both,16a10934e912,Grade 3,24,0.0,0,0,0,0,0,0,0,0.0,2488
35,Building removed,2c3581be6b5,Grade 5,30,0.0,0,0,0,0,0,0,0,1.0,3038
36,Building removed,f5e0e39b9c,Grade 5,10,0.0,0,0,0,0,0,0,0,1.0,1056
37,Exterior,11e64b184bf,Grade 2,12,0.0,0,0,0,0,0,0,0,0.0,1230
38,Exterior,2c3594b91c8,Grade 5,30,0.0,0,0,0,0,0,0,0,0.0,3038
39,Exterior,230ad59877a,Grade 5,24,0.0,0,0,0,0,0,0,0,0.0,2408
40,Building removed,40c90798bd3,Grade 5,44,0.0,0,0,0,0,0,0,0,1.0,4452
41,Both,39a05f85faf,Grade 2,39,0.0,0,0,0,0,0,0,0,1.0,3960
42,Building removed,4376ab5a107,Grade 5,46,0.0,0,0,0,0,0,0,0,1.0,4636
43,Building removed,34ff94ef6ee,Grade 5,36,1.0,1,0,0,0,0,0,0,0.0,3642
44,Both,23e2ca333c4,Grade 4,24,0.0,0,0,0,0,0,0,0,0.0,2466
45,Exterior,278ddc51d58,Grade 4,27,0.0,0,0,0,0,0,0,0,0.0,2718
46,Both,1d6925a0e23,Grade 4,20,0.0,0,0,0,0,0,0,0,0.0,2021
47,Both,2d32e69444f,Grade 2,31,0.0,0,0,0,0,0,0,0,0.0,3106
48,Both,12f283a4d56,Grade 4,13,0.0,0,0,0,0,0,0,0,0.0,1302
49,Building removed,22506235b3f,Grade 5,23,0.0,0,0,0,0,0,0,0,0.0,2358

In [4]:
train.describe()

,district_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,has_repair_started,vdcmun_id
count,631761.000000,631761.000000,631761.000000,631761.000000,631761.000000,631761.000000,631761.000000,631761.000000,631761.000000,598344.000000,631761.000000
mean,26.831720,0.123920,0.042708,0.009263,0.034602,0.069629,0.002319,0.001061,0.034853,0.316076,2712.186552
std,7.771394,0.329491,0.202197,0.095798,0.182769,0.254521,0.048099,0.032548,0.183408,0.464943,777.505768
min,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,701.000000
25%,22.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2242.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2703.000000
75%,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3119.000000
max,51.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5142.000000

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 631761 entries, 0 to 631760
Data columns (total 14 columns):
area_assesed                             631761 non-null object
building_id                              631761 non-null object
damage_grade                             631761 non-null object
district_id                              631761 non-null int64
has_geotechnical_risk                    631761 non-null float64
has_geotechnical_risk_fault_crack        631761 non-null int64
has_geotechnical_risk_flood              631761 non-null int64
has_geotechnical_risk_land_settlement    631761 non-null int64
has_geotechnical_risk_landslide          631761 non-null int64
has_geotechnical_risk_liquefaction       631761 non-null int64
has_geotechnical_risk_other              631761 non-null int64
has_geotechnical_risk_rock_fall          631761 non-null int64
has_repair_started                       598344 non-null float64
vdcmun_id                                631761 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 60.2+ MB

In [7]:

train.describe(include=['O'])

       area_assesed  building_id damage_grade
count        631761       631761       631761
unique            5       631761            5
top            Both  2223c130c56      Grade 5
freq         382992            1       210825

In [8]:
q= train.district_id
#q.describe()
q.value_counts()

24    58744
31    54665
30    53637
23    53223
36    46988
28    46226
20    41254
22    36307
21    34989
27    30810
12    23700
25    19976
26    18094
38    15178
37    13501
11    10353
39     9685
35     9175
13     7676
29     7573
40     6679
44     6552
47     6399
10     5600
46     4263
9      3049
7      2714
45     2338
51      975
43      843
48      595
Name: district_id, dtype: int64

In [10]:
#Make copies of both dataframes.
traindf = train.copy()
testdf = test.copy()
#Create list of both data frames to apply similar functions to.
all_data = [traindf, testdf]

In [11]:
train.damage_grade = train.damage_grade.str.slice(-1)
train.damage_grade=train.damage_grade.astype(int)

In [12]:

train.groupby('district_id',as_index=False).sum().sort_values(by='damage_grade')

,district_id,damage_grade,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,has_repair_started,vdcmun_id
29,48,2396,14.0,2,0,6,5,0,0,2,404.0,2875991
24,43,2606,68.0,0,21,2,62,0,0,34,521.0,3640748
30,51,2904,2.0,0,0,2,0,0,0,0,739.0,4997837
26,45,7336,60.0,1,0,1,56,0,0,7,1728.0,10587548
1,9,7771,169.0,47,1,70,79,0,0,15,2071.0,2788586
0,7,8626,189.0,6,0,137,53,0,0,12,1681.0,1950329
27,46,13019,229.0,44,27,33,126,2,1,38,2681.0,19802811
28,47,16793,374.0,32,19,38,230,0,75,80,4511.0,30306495
2,10,17527,677.0,85,0,174,421,1,5,168,3580.0,5752241
25,44,17742,485.0,13,9,24,402,3,6,288,4447.0,29014915
23,40,19333,529.0,46,68,103,387,7,12,49,4607.0,26893535
5,13,25108,761.0,317,27,465,561,3,1,241,4086.0,10274614
18,35,26073,597.0,114,82,134,323,2,2,110,5026.0,32297682
22,39,28622,588.0,90,19,146,450,9,4,98,6824.0,38096551
15,29,34390,2294.0,927,114,386,1599,9,20,1448,2347.0,22031438
3,11,34512,1022.0,173,45,179,599,30,0,514,6545.0,11590138
20,37,41876,1721.0,404,100,844,708,6,15,407,7515.0,50400181
21,38,43378,1211.0,147,18,360,917,6,9,185,8549.0,58030664
4,12,68037,3113.0,966,211,565,1755,120,20,882,7351.0,29106354
12,26,72998,641.0,81,6,153,468,18,2,16,5191.0,47131998
11,25,78817,1776.0,485,42,980,862,66,11,541,5568.0,50385937
6,20,118791,8287.0,1990,1265,2676,4777,170,135,1513,17798.0,83646335
7,21,124390,4203.0,1265,142,1230,2090,72,8,1489,6359.0,74457236
17,31,128187,6762.0,1288,1462,1506,4267,73,46,1759,15070.0,170659846
13,27,128401,1590.0,541,17,581,743,32,12,134,9665.0,83976808
8,22,156378,6082.0,3230,327,2031,2904,42,9,1528,3650.0,80791312
19,36,176630,6154.0,2310,287,1632,3387,534,19,2153,10430.0,170784405
14,28,196030,5422.0,2596,200,1452,2158,29,14,1153,9590.0,130811349
10,24,205175,5548.0,1967,213,1334,2452,199,222,695,12484.0,143652173
16,30,208545,5718.0,2853,203,1462,3345,11,17,2038,10708.0,162246466
9,23,249062,12002.0,4961,927,3154,7803,21,5,4422,7396.0,124471165

In [13]:
train['summ'] = train.groupby('district_id',as_index=False).sum()[['damage_grade']]
#train.district_id = train.groupby('district_id')['damage_grade'].transform('sum')
train.summ.describe()

count        31.000000
mean      72950.096774
std       74205.675130
min        2396.000000
25%       17160.000000
50%       34512.000000
75%      126288.500000
max      249062.000000
Name: summ, dtype: float64

In [14]:
#dividing disctricts into  different bins at points(2395,17160,34512,126288,249063)
train.district_id = pd.cut(train['summ'],bins=[2395,17160,34512,126288,249063],labels=['dis_catagory_1','dis_catagory_2','dis_catagory_3','dis_catagory_4'])

In [15]:
train=train.drop('vdcmun_id',axis=1) 
train=train.drop('building_id',axis=1)
train.head(20)

,area_assesed,damage_grade,district_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,has_repair_started,summ
0,Both,4,dis_catagory_1,0.0,0,0,0,0,0,0,0,0.0,8626.0
1,Both,2,dis_catagory_1,0.0,0,0,0,0,0,0,0,1.0,7771.0
2,Both,1,dis_catagory_2,0.0,0,0,0,0,0,0,0,0.0,17527.0
3,Building removed,5,dis_catagory_2,0.0,0,0,0,0,0,0,0,0.0,34512.0
4,Both,3,dis_catagory_3,0.0,0,0,0,0,0,0,0,0.0,68037.0
5,Exterior,5,dis_catagory_2,0.0,0,0,0,0,0,0,0,0.0,25108.0
6,Both,2,dis_catagory_3,1.0,0,0,0,1,0,0,1,0.0,118791.0
7,Both,5,dis_catagory_3,0.0,0,0,0,0,0,0,0,0.0,124390.0
8,Both,1,dis_catagory_4,0.0,0,0,0,0,0,0,0,NaN,156378.0
9,Both,3,dis_catagory_4,0.0,0,0,0,0,0,0,0,1.0,249062.0
10,Exterior,5,dis_catagory_4,0.0,0,0,0,0,0,0,0,0.0,205175.0
11,Both,4,dis_catagory_3,0.0,0,0,0,0,0,0,0,0.0,78817.0
12,Both,2,dis_catagory_3,0.0,0,0,0,0,0,0,0,1.0,72998.0
13,Building removed,5,dis_catagory_4,0.0,0,0,0,0,0,0,0,0.0,128401.0
14,Both,2,dis_catagory_4,0.0,0,0,0,0,0,0,0,1.0,196030.0
15,Both,5,dis_catagory_2,0.0,0,0,0,0,0,0,0,0.0,34390.0
16,Both,4,dis_catagory_4,0.0,0,0,0,0,0,0,0,1.0,208545.0
17,Both,3,dis_catagory_4,0.0,0,0,0,0,0,0,0,0.0,128187.0
18,Both,4,dis_catagory_2,0.0,0,0,0,0,0,0,0,1.0,26073.0
19,Exterior,3,dis_catagory_4,0.0,0,0,0,0,0,0,0,0.0,176630.0

In [16]:
train.fillna(method='ffill',inplace=True)

In [17]:

y = train.damage_grade
x= train.drop('damage_grade',axis=1)
x= train.drop('summ',axis=1)

In [18]:
x = pd.get_dummies(x)

In [19]:
x.head()

,damage_grade,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,has_repair_started,area_assesed_Both,area_assesed_Building removed,area_assesed_Exterior,area_assesed_Interior,area_assesed_Not able to inspect,district_id_dis_catagory_1,district_id_dis_catagory_2,district_id_dis_catagory_3,district_id_dis_catagory_4
0,4,0.0,0,0,0,0,0,0,0,0.0,1,0,0,0,0,1,0,0,0
1,2,0.0,0,0,0,0,0,0,0,1.0,1,0,0,0,0,1,0,0,0
2,1,0.0,0,0,0,0,0,0,0,0.0,1,0,0,0,0,0,1,0,0
3,5,0.0,0,0,0,0,0,0,0,0.0,0,1,0,0,0,0,1,0,0
4,3,0.0,0,0,0,0,0,0,0,0.0,1,0,0,0,0,0,0,1,0

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [21]:
train_x, val_x, train_y, val_y = train_test_split(x,y,random_state = 0)

In [22]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(penalty='l2', C=1)

In [24]:
model.fit(train_x,train_y)

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [25]:
model.predict(val_x)

array([4, 2, 4, ..., 1, 5, 4])

In [26]:
print("Logistic accruracy %2.2f "%accuracy_score(val_y,model.predict(val_x)))

Logistic accruracy 0.94

In [27]:
from sklearn.tree import DecisionTreeClassifier

# Define model
train_model = DecisionTreeClassifier()
train_model.fit(train_x,train_y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [32]:
train_model.score(val_x, val_y)

1.0

In [29]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(train_x,train_y)

GaussianNB(priors=None)

In [30]:
model.score(val_x, val_y)

1.0